# Generated by Django 6.0.2 on 2026-02-07 09:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppVarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='apps/')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('SM', 'Social Media'), ('EC', 'E-commerce'), ('FH', 'Fitness and Health'), ('BK', 'Banking')], max_length=2)),
            ],
        ),
    ]
