# Generated by Django 6.0.2 on 2026-02-07 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appvarity',
            name='descriptions',
            field=models.TextField(default=''),
        ),
    ]
